spring:
  datasource:
    url: jdbc:mysql://localhost/vpms?serverTimezone=UTC#
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Siddharth123
server:
  servlet:
    context-path: /vpms